// Code generated by "stringer -type=ClusterType"; DO NOT EDIT.

package pav

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClusterShortest-1]
	_ = x[ClusterBound-2]
}

const _ClusterType_name = "ClusterShortestClusterBound"

var _ClusterType_index = [...]uint8{0, 15, 27}

func (i ClusterType) String() string {
	i -= 1
	if i >= ClusterType(len(_ClusterType_index)-1) {
		return "ClusterType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ClusterType_name[_ClusterType_index[i]:_ClusterType_index[i+1]]
}
