// Code generated by "stringer -type=Op"; DO NOT EDIT.

package pav

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpRune-1]
	_ = x[OpCall-2]
	_ = x[OpJump-3]
	_ = x[OpClone-4]
	_ = x[OpReturn-5]
	_ = x[OpIndirect-6]
}

const _Op_name = "OpRuneOpCallOpJumpOpCloneOpReturnOpIndirect"

var _Op_index = [...]uint8{0, 6, 12, 18, 25, 33, 43}

func (i Op) String() string {
	i -= 1
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
